# Bank data ANN (Categorical)

Data preprocessing

In [1]:
# 1. Importing the libraries 
import numpy as np 
import pandas as pd

In [2]:
# 2. Reading the datasets 
data = pd.read_csv('bank.csv')

In [3]:
data.head(30)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
5,42,management,single,tertiary,no,0,yes,yes,unknown,5,may,562,2,-1,0,unknown,yes
6,56,management,married,tertiary,no,830,yes,yes,unknown,6,may,1201,1,-1,0,unknown,yes
7,60,retired,divorced,secondary,no,545,yes,no,unknown,6,may,1030,1,-1,0,unknown,yes
8,37,technician,married,secondary,no,1,yes,no,unknown,6,may,608,1,-1,0,unknown,yes
9,28,services,single,secondary,no,5090,yes,no,unknown,6,may,1297,3,-1,0,unknown,yes
10,38,admin.,single,secondary,no,100,yes,no,unknown,7,may,786,1,-1,0,unknown,yes
11,30,blue-collar,married,secondary,no,309,yes,no,unknown,7,may,1574,2,-1,0,unknown,yes
12,29,management,married,tertiary,no,199,yes,yes,unknown,7,may,1689,4,-1,0,unknown,yes
13,46,blue-collar,single,tertiary,no,460,yes,no,unknown,7,may,1102,2,-1,0,unknown,yes
14,31,technician,single,tertiary,no,703,yes,no,unknown,8,may,943,2,-1,0,unknown,yes
15,35,management,divorced,tertiary,no,3837,yes,no,unknown,8,may,1084,1,-1,0,unknown,yes
16,32,blue-collar,single,primary,no,611,yes,no,unknown,8,may,541,3,-1,0,unknown,yes
17,49,services,married,secondary,no,-8,yes,no,unknown,8,may,1119,1,-1,0,unknown,yes
18,41,admin.,married,secondary,no,55,yes,no,unknown,8,may,1120,2,-1,0,unknown,yes
19,49,admin.,divorced,secondary,no,168,yes,yes,unknown,8,may,513,1,-1,0,unknown,yes
20,28,admin.,divorced,secondary,no,785,yes,no,unknown,8,may,442,2,-1,0,unknown,yes
21,43,management,single,tertiary,no,2067,yes,no,unknown,8,may,756,1,-1,0,unknown,yes
22,43,management,divorced,tertiary,no,388,yes,no,unknown,8,may,2087,2,-1,0,unknown,yes
23,43,blue-collar,married,primary,no,-192,yes,no,unknown,8,may,1120,2,-1,0,unknown,yes
24,37,unemployed,single,secondary,no,381,yes,no,unknown,8,may,985,2,-1,0,unknown,yes
25,35,blue-collar,single,secondary,no,40,yes,no,unknown,9,may,617,4,-1,0,unknown,yes
26,31,technician,single,tertiary,no,22,yes,no,unknown,9,may,483,3,-1,0,unknown,yes
27,43,blue-collar,single,secondary,no,3,yes,no,unknown,9,may,929,3,-1,0,unknown,yes
28,31,admin.,married,secondary,no,307,yes,no,unknown,9,may,538,1,-1,0,unknown,yes
29,28,blue-collar,single,secondary,no,759,yes,no,unknown,9,may,710,1,-1,0,unknown,yes

In [4]:
# 3. Handling missing values 
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

The dataset has no missing values in any of the columns

In [5]:
# 4. Splitting data into inputs and outputs
inputs = data.iloc[:, :16].values
outputs = data.iloc[:, -1:].values

In [6]:
inputs[0:2]

array([[59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
        'unknown', 5, 'may', 1042, 1, -1, 0, 'unknown'],
       [56, 'admin.', 'married', 'secondary', 'no', 45, 'no', 'no',
        'unknown', 5, 'may', 1467, 1, -1, 0, 'unknown']], dtype=object)

In [7]:
outputs.shape

(11162, 1)

In [8]:
outputs

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [9]:
# Importing libraries to handle the categorical data 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [10]:
# 5. Handling categorical data 
ct = ColumnTransformer([('one', OneHotEncoder(), [1,2,3,4,6,7,8,10,15])], remainder = 'passthrough')
inputs = ct.fit_transform(inputs)

cto = ColumnTransformer([('one', OneHotEncoder(), [0])], remainder = 'passthrough')
outputs = cto.fit_transform(outputs)

In [11]:
inputs.shape

(11162, 51)

In [12]:
inputs

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [13]:
outputs

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [14]:
# Importing libraries to handle splitting 
from sklearn.model_selection import train_test_split

In [15]:
# 6. Splitting data to train and test sets
x_train,x_test,y_train,y_test = train_test_split(inputs,outputs,test_size = 0.2, random_state = 0)

In [16]:
print('Inputs shape ', inputs.shape)
print('Outputs shape ', outputs.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

Inputs shape  (11162, 51)
Outputs shape  (11162, 2)
x_train shape  (8929, 51)
x_test shape  (2233, 51)
y_train shape  (8929, 2)
y_test shape (2233, 2)

In [17]:
# Importing libraries to handle feature scaling 
from sklearn.preprocessing import StandardScaler

In [18]:
# 7. Applying feature scaling 
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [19]:
x_train

array([[-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192,  2.18530314, -0.17658264, ...,  0.92827075,
        -0.48428507, -0.35888264],
       ...,
       [-0.37172192, -0.45760242, -0.17658264, ...,  2.04743488,
        -0.48428507, -0.35888264],
       [ 2.69018306, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264]])

In [20]:
x_test

array([[-0.35506564, -0.46571851, -0.16329932, ..., -0.51893725,
         2.62409874,  0.62465525],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.51893725,
         1.30248101,  1.63872661],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612],
       ...,
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612],
       [ 2.81638066, -0.46571851, -0.16329932, ..., -0.51893725,
        -0.46885387, -0.38941612],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612]])

ANN Modelling

In [21]:
# Import deep learning libraries
from tensorflow.keras.models import Sequential  
from tensorflow.keras.layers import Dense

In [22]:
categorical = Sequential()

In [23]:
# Input layer
categorical.add(Dense(units = 51, kernel_initializer = 'random_uniform', activation = 'relu'))

In [24]:
# Hidden layer 1  
categorical.add(Dense(units = 102, kernel_initializer = 'random_uniform', activation = 'relu'))

In [25]:
# Hidden layer 2
categorical.add(Dense(units = 102, kernel_initializer = 'random_uniform', activation = 'relu'))

In [26]:
# Output layer 
categorical.add(Dense(units = 2, kernel_initializer = 'random_uniform', activation = 'softmax'))

In [27]:
# Compiling model  
categorical.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [28]:
# Training the model 
categorical.fit(x_train, y_train, epochs = 150)

Epoch 1/150
280/280 [==============================] - 1s 741us/step - loss: 0.4381 - accuracy: 0.7954
Epoch 2/150
280/280 [==============================] - 0s 717us/step - loss: 0.3605 - accuracy: 0.8490
Epoch 3/150
280/280 [==============================] - 0s 781us/step - loss: 0.3431 - accuracy: 0.8565
Epoch 4/150
280/280 [==============================] - 0s 623us/step - loss: 0.3325 - accuracy: 0.8611
Epoch 5/150
280/280 [==============================] - 0s 711us/step - loss: 0.3334 - accuracy: 0.85910s - loss: 0.3376 - accuracy: 0.
Epoch 6/150
280/280 [==============================] - 0s 716us/step - loss: 0.3162 - accuracy: 0.8680
Epoch 7/150
280/280 [==============================] - 0s 720us/step - loss: 0.3086 - accuracy: 0.8702
Epoch 8/150
280/280 [==============================] - 0s 715us/step - loss: 0.3043 - accuracy: 0.8734
Epoch 9/150
280/280 [==============================] - 0s 719us/step - loss: 0.2977 - accuracy: 0.8797
Epoch 10/150
280/280 [==============================] - 0s 733us/step - loss: 0.2936 - accuracy: 0.8785
Epoch 11/150
280/280 [==============================] - 0s 817us/step - loss: 0.2885 - accuracy: 0.8793
Epoch 12/150
280/280 [==============================] - 0s 855us/step - loss: 0.2803 - accuracy: 0.8824
Epoch 13/150
280/280 [==============================] - 0s 746us/step - loss: 0.2807 - accuracy: 0.8839
Epoch 14/150
280/280 [==============================] - 0s 685us/step - loss: 0.2718 - accuracy: 0.8858
Epoch 15/150
280/280 [==============================] - 0s 850us/step - loss: 0.2686 - accuracy: 0.8901
Epoch 16/150
280/280 [==============================] - 0s 756us/step - loss: 0.2621 - accuracy: 0.8902
Epoch 17/150
280/280 [==============================] - 0s 786us/step - loss: 0.2600 - accuracy: 0.8918
Epoch 18/150
280/280 [==============================] - 0s 717us/step - loss: 0.2521 - accuracy: 0.8935
Epoch 19/150
280/280 [==============================] - 0s 718us/step - loss: 0.2582 - accuracy: 0.8933
Epoch 20/150
280/280 [==============================] - 0s 769us/step - loss: 0.2443 - accuracy: 0.8969
Epoch 21/150
280/280 [==============================] - 0s 746us/step - loss: 0.2335 - accuracy: 0.8995
Epoch 22/150
280/280 [==============================] - 0s 692us/step - loss: 0.2358 - accuracy: 0.8982
Epoch 23/150
280/280 [==============================] - 0s 765us/step - loss: 0.2281 - accuracy: 0.9036
Epoch 24/150
280/280 [==============================] - 0s 744us/step - loss: 0.2206 - accuracy: 0.9037
Epoch 25/150
280/280 [==============================] - 0s 725us/step - loss: 0.2144 - accuracy: 0.9070
Epoch 26/150
280/280 [==============================] - 0s 687us/step - loss: 0.2109 - accuracy: 0.9076
Epoch 27/150
280/280 [==============================] - 0s 716us/step - loss: 0.2058 - accuracy: 0.9124
Epoch 28/150
280/280 [==============================] - 0s 814us/step - loss: 0.2003 - accuracy: 0.91150s - loss: 0.1813 - accuracy
Epoch 29/150
280/280 [==============================] - 0s 777us/step - loss: 0.1933 - accuracy: 0.9165
Epoch 30/150
280/280 [==============================] - 0s 714us/step - loss: 0.1928 - accuracy: 0.9159
Epoch 31/150
280/280 [==============================] - 0s 764us/step - loss: 0.1846 - accuracy: 0.9203
Epoch 32/150
280/280 [==============================] - 0s 818us/step - loss: 0.1782 - accuracy: 0.9228
Epoch 33/150
280/280 [==============================] - 0s 658us/step - loss: 0.1741 - accuracy: 0.9207
Epoch 34/150
280/280 [==============================] - 0s 695us/step - loss: 0.1710 - accuracy: 0.9245
Epoch 35/150
280/280 [==============================] - 0s 676us/step - loss: 0.1660 - accuracy: 0.9262
Epoch 36/150
280/280 [==============================] - 0s 638us/step - loss: 0.1557 - accuracy: 0.9319
Epoch 37/150
280/280 [==============================] - 0s 669us/step - loss: 0.1563 - accuracy: 0.9310
Epoch 38/150
280/280 [==============================] - 0s 658us/step - loss: 0.1532 - accuracy: 0.9330
Epoch 39/150
280/280 [==============================] - 0s 730us/step - loss: 0.1432 - accuracy: 0.9385
Epoch 40/150
280/280 [==============================] - 0s 605us/step - loss: 0.1364 - accuracy: 0.9412
Epoch 41/150
280/280 [==============================] - 0s 833us/step - loss: 0.1324 - accuracy: 0.9417
Epoch 42/150
280/280 [==============================] - 0s 965us/step - loss: 0.1325 - accuracy: 0.9421
Epoch 43/150
280/280 [==============================] - ETA: 0s - loss: 0.1396 - accuracy: 0.94 - 0s 894us/step - loss: 0.1392 - accuracy: 0.9400
Epoch 44/150
280/280 [==============================] - 0s 785us/step - loss: 0.1295 - accuracy: 0.9439
Epoch 45/150
280/280 [==============================] - 0s 725us/step - loss: 0.1164 - accuracy: 0.9496
Epoch 46/150
280/280 [==============================] - 0s 751us/step - loss: 0.1224 - accuracy: 0.9461
Epoch 47/150
280/280 [==============================] - 0s 944us/step - loss: 0.1127 - accuracy: 0.95050s - loss: 0.1040 - accuracy:
Epoch 48/150
280/280 [==============================] - 0s 883us/step - loss: 0.1129 - accuracy: 0.9504
Epoch 49/150
280/280 [==============================] - 0s 715us/step - loss: 0.1666 - accuracy: 0.9269
Epoch 50/150
280/280 [==============================] - 0s 752us/step - loss: 0.1172 - accuracy: 0.9467
Epoch 51/150
280/280 [==============================] - 0s 752us/step - loss: 0.1065 - accuracy: 0.9527
Epoch 52/150
280/280 [==============================] - 0s 703us/step - loss: 0.0960 - accuracy: 0.9586
Epoch 53/150
280/280 [==============================] - 0s 880us/step - loss: 0.0873 - accuracy: 0.9615
Epoch 54/150
280/280 [==============================] - 0s 869us/step - loss: 0.1031 - accuracy: 0.9533
Epoch 55/150
280/280 [==============================] - 0s 774us/step - loss: 0.0948 - accuracy: 0.9586
Epoch 56/150
280/280 [==============================] - 0s 768us/step - loss: 0.0859 - accuracy: 0.9625
Epoch 57/150
280/280 [==============================] - 0s 695us/step - loss: 0.0806 - accuracy: 0.9648
Epoch 58/150
280/280 [==============================] - 0s 903us/step - loss: 0.0968 - accuracy: 0.9600
Epoch 59/150
280/280 [==============================] - 0s 833us/step - loss: 0.0998 - accuracy: 0.9588
Epoch 60/150
280/280 [==============================] - 0s 933us/step - loss: 0.0781 - accuracy: 0.9649
Epoch 61/150
280/280 [==============================] - 0s 727us/step - loss: 0.0871 - accuracy: 0.9646
Epoch 62/150
280/280 [==============================] - 0s 737us/step - loss: 0.0955 - accuracy: 0.95970s - loss: 0.0960 - accuracy: 0.
Epoch 63/150
280/280 [==============================] - 0s 773us/step - loss: 0.0705 - accuracy: 0.9695
Epoch 64/150
280/280 [==============================] - 0s 853us/step - loss: 0.0721 - accuracy: 0.9700
Epoch 65/150
280/280 [==============================] - 0s 785us/step - loss: 0.0689 - accuracy: 0.9739
Epoch 66/150
280/280 [==============================] - 0s 778us/step - loss: 0.0723 - accuracy: 0.9694
Epoch 67/150
280/280 [==============================] - 0s 805us/step - loss: 0.0851 - accuracy: 0.9667
Epoch 68/150
280/280 [==============================] - 0s 839us/step - loss: 0.0752 - accuracy: 0.9688
Epoch 69/150
280/280 [==============================] - 0s 843us/step - loss: 0.0542 - accuracy: 0.9773
Epoch 70/150
280/280 [==============================] - 0s 871us/step - loss: 0.0549 - accuracy: 0.9786
Epoch 71/150
280/280 [==============================] - 0s 881us/step - loss: 0.0675 - accuracy: 0.9740
Epoch 72/150
280/280 [==============================] - 0s 885us/step - loss: 0.0715 - accuracy: 0.9712
Epoch 73/150
280/280 [==============================] - 0s 903us/step - loss: 0.0583 - accuracy: 0.97650s - loss: 0.0617 - accuracy
Epoch 74/150
280/280 [==============================] - 0s 782us/step - loss: 0.0687 - accuracy: 0.9742
Epoch 75/150
280/280 [==============================] - 0s 718us/step - loss: 0.0639 - accuracy: 0.9774
Epoch 76/150
280/280 [==============================] - 0s 853us/step - loss: 0.0508 - accuracy: 0.9811
Epoch 77/150
280/280 [==============================] - 0s 790us/step - loss: 0.0577 - accuracy: 0.9782
Epoch 78/150

280/280 [==============================] - 0s 986us/step - loss: 0.0857 - accuracy: 0.9705
Epoch 79/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0598 - accuracy: 0.9761
Epoch 80/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0534 - accuracy: 0.9815
Epoch 81/150
280/280 [==============================] - 0s 862us/step - loss: 0.0363 - accuracy: 0.9869
Epoch 82/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0368 - accuracy: 0.9860
Epoch 83/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0466 - accuracy: 0.9838: 0s - loss: 0.0379 - accuracy:
Epoch 84/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0531 - accuracy: 0.9785
Epoch 85/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0545 - accuracy: 0.9801
Epoch 86/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0544 - accuracy: 0.9807
Epoch 87/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0398 - accuracy: 0.9840
Epoch 88/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0407 - accuracy: 0.9838
Epoch 89/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0507 - accuracy: 0.9844
Epoch 90/150
280/280 [==============================] - 0s 1ms/step - loss: 0.1192 - accuracy: 0.9614
Epoch 91/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0513 - accuracy: 0.9788
Epoch 92/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0323 - accuracy: 0.9886
Epoch 93/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0251 - accuracy: 0.9901
Epoch 94/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0325 - accuracy: 0.9894
Epoch 95/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0401 - accuracy: 0.9866
Epoch 96/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0280 - accuracy: 0.9890
Epoch 97/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0270 - accuracy: 0.9909
Epoch 98/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0433 - accuracy: 0.9831
Epoch 99/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0620 - accuracy: 0.9793
Epoch 100/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0706 - accuracy: 0.9751
Epoch 101/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0518 - accuracy: 0.9810
Epoch 102/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0452 - accuracy: 0.9853
Epoch 103/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0301 - accuracy: 0.9910
Epoch 104/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0259 - accuracy: 0.9919
Epoch 105/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0258 - accuracy: 0.9914
Epoch 106/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0165 - accuracy: 0.9938
Epoch 107/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0234 - accuracy: 0.9922
Epoch 108/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0609 - accuracy: 0.9817
Epoch 109/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0693 - accuracy: 0.9750
Epoch 110/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0359 - accuracy: 0.9879
Epoch 111/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0228 - accuracy: 0.9914
Epoch 112/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0199 - accuracy: 0.9931
Epoch 113/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0197 - accuracy: 0.9947
Epoch 114/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0369 - accuracy: 0.9876
Epoch 115/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0370 - accuracy: 0.9882
Epoch 116/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0428 - accuracy: 0.9873
Epoch 117/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0731 - accuracy: 0.9767
Epoch 118/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0457 - accuracy: 0.9857
Epoch 119/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0271 - accuracy: 0.9916
Epoch 120/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0167 - accuracy: 0.9951
Epoch 121/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0149 - accuracy: 0.9955
Epoch 122/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0163 - accuracy: 0.9945
Epoch 123/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0194 - accuracy: 0.9940
Epoch 124/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0312 - accuracy: 0.9877
Epoch 125/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0653 - accuracy: 0.9764
Epoch 126/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0395 - accuracy: 0.9850
Epoch 127/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0436 - accuracy: 0.9849
Epoch 128/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0193 - accuracy: 0.9935
Epoch 129/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0105 - accuracy: 0.9965
Epoch 130/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0116 - accuracy: 0.9963
Epoch 131/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0176 - accuracy: 0.9940
Epoch 132/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0661 - accuracy: 0.9788
Epoch 133/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0462 - accuracy: 0.9838
Epoch 134/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0267 - accuracy: 0.9920
Epoch 135/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0195 - accuracy: 0.9928
Epoch 136/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0163 - accuracy: 0.9945
Epoch 137/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0438 - accuracy: 0.9848
Epoch 138/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0248 - accuracy: 0.9912
Epoch 139/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0254 - accuracy: 0.9915
Epoch 140/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0205 - accuracy: 0.9945
Epoch 141/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0166 - accuracy: 0.9947
Epoch 142/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0167 - accuracy: 0.9942
Epoch 143/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0367 - accuracy: 0.9890
Epoch 144/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0537 - accuracy: 0.9814
Epoch 145/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0388 - accuracy: 0.9861
Epoch 146/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0144 - accuracy: 0.9952
Epoch 147/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0090 - accuracy: 0.9975
Epoch 148/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0075 - accuracy: 0.9976
Epoch 149/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0071 - accuracy: 0.9976
Epoch 150/150
280/280 [==============================] - 0s 1ms/step - loss: 0.0165 - accuracy: 0.9950

In [29]:
# Testing the model with test set 
ypred = categorical.predict(x_test)

In [30]:
ypred[0]

array([1.0000000e+00, 1.0280164e-20], dtype=float32)

In [31]:
ypred[0]>0.5

array([ True, False])

In [32]:
data.head(100)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,37,management,divorced,tertiary,no,122,yes,no,unknown,19,may,1622,2,-1,0,unknown,yes
96,30,technician,single,tertiary,no,880,yes,yes,unknown,19,may,967,6,-1,0,unknown,yes
97,41,technician,married,secondary,no,501,yes,no,unknown,19,may,579,5,-1,0,unknown,yes
98,36,blue-collar,married,secondary,no,4438,yes,no,unknown,20,may,446,1,-1,0,unknown,yes
99,35,blue-collar,divorced,secondary,no,0,yes,no,unknown,20,may,1205,1,-1,0,unknown,yes

In [33]:
# Testing the model with individual data 
yp = categorical.predict(sc.transform(ct.transform([[40, "management", "married", "secondary", "no", 4025, "yes", "no", "cellular", 15, "jul", 107, 4, -1, 0, "unknown"]])))

In [34]:
yp

array([[9.9999475e-01, 5.2138116e-06]], dtype=float32)

In [35]:
# Defining a list of categories to present the output in string 
deposits = ['No', 'Yes']
prediction = deposits[np.argmax(yp)]
prediction

'No'

In [36]:
np.argmax(yp)

0